[workspace]
members = ["cprof", "cprof-macros"]
default-members = ["cprof"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.89"
authors = ["haukzero <haukzero1@gmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/haukzero/cprof"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"
panic = "abort"
