use std::{
    env, fs,
    path::{Path, PathBuf},
};

use syn::{ForeignItem, Item, UseTree};

const DISPATCH_ENTRY: &str = "__cprof_dispatch_run";

fn main() {
    if let Err(error) = check_command_sources() {
        panic!("command source check failed: {error}");
    }
}

fn check_command_sources() -> Result<(), String> {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?);
    for group in ["root", "target"] {
        let directory = manifest.join("src/commands").join(group);
        let module_file = directory.join("mod.rs");
        let modules = parse_file(&module_file)?;
        for item in modules.items {
            let Item::Mod(module) = item else {
                return Err(format!(
                    "{}: expected only command module declarations",
                    module_file.display()
                ));
            };
            if module.content.is_some() || !module.attrs.is_empty() {
                return Err(format!(
                    "{}: command modules must use the default external module file",
                    module_file.display()
                ));
            }
            let source_file = directory.join(format!("{}.rs", module.ident));
            check_command_file(&source_file)?;
        }
    }
    Ok(())
}

fn parse_file(path: &Path) -> Result<syn::File, String> {
    println!("cargo:rerun-if-changed={}", path.display());
    let source =
        fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    syn::parse_file(&source).map_err(|error| format!("{}: {error}", path.display()))
}

fn check_command_file(path: &Path) -> Result<(), String> {
    let file = parse_file(path)?;
    let mut has_run = false;
    for item in file.items {
        match item {
            Item::Fn(function) if function.sig.ident == "run" => has_run = true,
            Item::Fn(function) if function.sig.ident == DISPATCH_ENTRY => {
                return Err(format!(
                    "{}: {DISPATCH_ENTRY} must be generated by #[cprof_macros::command]",
                    path.display()
                ));
            }
            Item::Const(item) if item.ident == DISPATCH_ENTRY => {
                return Err(format!(
                    "{}: {DISPATCH_ENTRY} cannot be declared here",
                    path.display()
                ));
            }
            Item::Static(item) if item.ident == DISPATCH_ENTRY => {
                return Err(format!(
                    "{}: {DISPATCH_ENTRY} cannot be declared here",
                    path.display()
                ));
            }
            Item::ForeignMod(item)
                if item.items.iter().any(|item| {
                    matches!(item, ForeignItem::Fn(function) if function.sig.ident == DISPATCH_ENTRY)
                }) =>
            {
                return Err(format!(
                    "{}: {DISPATCH_ENTRY} cannot be declared here",
                    path.display()
                ));
            }
            Item::Use(item) if imports_name(&item.tree, DISPATCH_ENTRY) => {
                return Err(format!(
                    "{}: {DISPATCH_ENTRY} cannot be imported here",
                    path.display()
                ));
            }
            Item::Macro(_) => {
                return Err(format!(
                    "{}: module-scope macros are not allowed in command files",
                    path.display()
                ));
            }
            Item::Verbatim(_) => {
                return Err(format!(
                    "{}: unsupported module item in command file",
                    path.display()
                ));
            }
            _ => {}
        }
    }
    if !has_run {
        return Err(format!(
            "{}: command module must define fn run",
            path.display()
        ));
    }
    Ok(())
}

fn imports_name(tree: &UseTree, name: &str) -> bool {
    match tree {
        UseTree::Path(path) => imports_name(&path.tree, name),
        UseTree::Name(item) => item.ident == name,
        UseTree::Rename(item) => item.rename == name,
        UseTree::Group(group) => group.items.iter().any(|item| imports_name(item, name)),
        UseTree::Glob(_) => true,
    }
}
